bikeprofiles:
  roadbike:
    speeds:
      "31": 10.0
      "30": 4.5
      "27": 6.0
      "24": 7.5
      "21": 9.0
      "18": 10.5
      "15": 12.0
      "12": 13.5
      "9": 15.0
      "6": 16.5
      "3": 18.0
      "0": 25.0
      "-3": 28.0
      "-6": 31.0
      "-9": 34.0
      "-12": 37.0
      "-15": 40.0
      "-18": 43.0
      "-21": 46.0
      "-24": 49.0
      "-27": 52.0
      "-30": 60.0
      "min": 35.0
  gravel:
    speeds:
      "31": 8.0
      "30": 3.5
      "27": 5.0
      "24": 6.5
      "21": 8.0
      "18": 9.5
      "15": 11.0
      "12": 12.5
      "9": 14.0
      "6": 15.5
      "3": 17.0
      "0": 24.0
      "-3": 27.0
      "-6": 30.0
      "-9": 33.0
      "-12": 36.0
      "-15": 39.0
      "-18": 42.0
      "-21": 45.0
      "-24": 48.0
      "-27": 51.0
      "-30": 59.0
      "min": 34.0
  mtb:
    speeds:
      "31": 6.0
      "30": 2.5
      "27": 4.0
      "24": 5.5
      "21": 7.0
      "18": 8.5
      "15": 10.0
      "12": 11.5
      "9": 13.0
      "6": 14.5
      "3": 16.0
      "0": 23.0
      "-3": 26.0
      "-6": 29.0
      "-9": 32.0
      "-12": 35.0
      "-15": 38.0
      "-18": 41.0
      "-21": 44.0
      "-24": 47.0
      "-27": 50.0
      "-30": 58.0
      "min": 33.0
